### ISSUE TITLE
JDK Version during build does not match Java Version in Docker Image

### ISSUE THREAD

**Issue by HansG89** [eclipse-basyx/basyx-java-components#117]
Since version 1.2 of BaSyx the provided docker images of Regsitry and AASServer do not work anymore.
The immediately terminate with the following error:

```

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/eclipse/basyx/components/registry/executable/RegistryExecutable has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
```

This is because the applications have been [built](https://github.com/eclipse-basyx/basyx-java-components/blob/main/.github/workflows/maven-publish-snapshot.yml#L41) using JDK version 11 but the [docker images](https://github.com/eclipse-basyx/basyx-java-components/blob/main/basyx.components/basyx.components.docker/basyx.components.registry/Dockerfile#L1) are using JDK version 8.
Please adapt docker images to also use JDK version 11.

**Comment by FrankSchnicke** [comment]
Thanks for pointing this out. We fixed the images and pushed the correct version of the 1.2.0 images. 
Furthermore, we will adapt our processes to ensure that this kind of error will be caught in future.
