### ISSUE TITLE
AAS server failing when loading from AASX source and MQTT enabled

### ISSUE THREAD

**Issue by gitmpje** [eclipse-basyx/basyx-java-components#122]
When starting the server using the docker image (1.2.0) with the following settings:
- `aas.events=MQTT`
- `aas.source=01_Festo.aasx`

The following exception is thrown:
```
Exception in thread "main" java.lang.RuntimeException: Could not find parent reference for the submodel 'DeviceDescriptionFiles'
        at org.eclipse.basyx.extensions.submodel.mqtt.MqttSubmodelAPIHelper.getAASId(MqttSubmodelAPIHelper.java:64)
        at org.eclipse.basyx.extensions.submodel.mqtt.MqttDecoratingSubmodelAPIFactory.getSubmodelAPI(MqttDecoratingSubmodelAPIFactory.java:54)
        at org.eclipse.basyx.submodel.restapi.api.ISubmodelAPIFactory.create(ISubmodelAPIFactory.java:47)
        at org.eclipse.basyx.submodel.aggregator.SubmodelAggregator.updateSubmodel(SubmodelAggregator.java:68)
        at org.eclipse.basyx.submodel.aggregator.SubmodelAggregator.createSubmodel(SubmodelAggregator.java:63)
        at org.eclipse.basyx.submodel.aggregator.observing.ObservableSubmodelAggregator.createSubmodel(ObservableSubmodelAggregator.java:84)
        at org.eclipse.basyx.aas.restapi.MultiSubmodelProvider.createSubmodel(MultiSubmodelProvider.java:239)
        at org.eclipse.basyx.aas.restapi.MultiSubmodelProvider.setValue(MultiSubmodelProvider.java:366)
        at org.eclipse.basyx.aas.bundle.AASBundleHelper.integrate(AASBundleHelper.java:102)
        at org.eclipse.basyx.components.aas.AASServerComponent.createAggregatorServlet(AASServerComponent.java:449)
        at org.eclipse.basyx.components.aas.AASServerComponent.startComponent(AASServerComponent.java:234)
        at org.eclipse.basyx.components.aas.executable.AASServerExecutable.main(AASServerExecutable.java:67)
```

I did not observe this issue using the same configuration with version 1.1.0, and also when disabling MQTT (`aas.events=None`), no expection is thrown.

**Comment by HansG89** [comment]
I also had the same behavior.  
This is because the Submodels in the AAS did not contain the "parent" reference. Looking at the Meta Model 2/3 this property is not mendatory. So it should work without.
It seems like loading an AASX file without parent references works as expected but somewhere in the MQTT implementation this property is used without any fallback if it's not present.

**Comment by FrankSchnicke** [comment]
Many thanks for providing a demo aasx file. We will take a look at it and update this ticket

**Comment by gitmpje** [comment]
@HansG89 Thank you for providing the example. Indeed adding parent references to the submodels solves this issue.

Now it is possible to use version 1.2.0, which supports the `accessControlAllowOrigin` option, I was eager to try the [aas-gui](https://github.com/eclipse-basyx/basyx-applications/tree/main/aas-gui). It works quite nicely and I'm able to check the AAS structure and values. However, when trying to update a value an error is thrown.
Looking at the network requests, the GUI first makes an HTTP OPTIONS before the PUT request. I expect the issue is that OPTIONS is not in the allowed methods (https://github.com/eclipse-basyx/basyx-java-sdk/blob/1b6a7eb1c7d632cc2e0659614a1673755c766b51/src/main/java/org/eclipse/basyx/vab/protocol/http/server/BasysHTTPServlet.java#L93), is that on purpose? Or did I miss some setting?

**Comment by FrankSchnicke** [comment]
The missing OPTIONS is an oversight on our end. We will address this most likely in the next bugfix release.

**Comment by FrankSchnicke** [comment]
https://github.com/eclipse-basyx/basyx-java-sdk/pull/110 adds the necessary header type. However, OPTIONS was not required. What did steps did you do in the UI to trigger the OPTIONS request?

**Comment by gitmpje** [comment]
Sorry, I realize now that was a confusing statement, as the OPTIONS request is of course used for the access control. I expect that adding the `content-type` header should solve the problem, as that is the header type requested in this OPTIONS request (for the subsequent PUT request to update the value).

**Comment by FrankSchnicke** [comment]
Both issues are addressed and will be included in the upcoming release. Many thanks again for pointing it out and providing examples!
